security:
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: true

    encoders:
        Sulu\Bundle\SecurityBundle\Entity\User: bcrypt

    providers:
        sulu:
            id: sulu_security.user_provider

    access_control:
        - { path: ^/admin/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/security/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/translations, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/p/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_USER }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin(\/|$)
            anonymous: true
            lazy: true
            provider: sulu
            entry_point: sulu_security.authentication_entry_point
            json_login:
                check_path: sulu_admin.login_check
                success_handler: sulu_security.authentication_handler
                failure_handler: sulu_security.authentication_handler
            logout:
                path: sulu_admin.logout
                success_handler: sulu_security.logout_success_handler

#        website:
#            pattern: ^/
#            anonymous: lazy
#            # The login and logout routes need to be created.
#            # For an advanced user management with registration and opt-in emails have a look at the:
#            # https://github.com/sulu/SuluCommunityBundle
#            # Also have a look at the user context based caching when you output user role specific data
#            # https://docs.sulu.io/en/2.2/cookbook/user-context-caching.html
#            form_login:
#                login_path: login
#                check_path: login
#            logout:
#                path: logout
#                target: /
#            remember_me:
#                secret:   "%kernel.secret%"
#                lifetime: 604800 # 1 week in seconds
#                path:     /

sulu_security:
    checker:
        enabled: true

when@test:
    security:
        providers:
            sulu:
                id: test_user_provider

        firewalls:
            admin:
                http_basic:
                    provider: sulu

    sulu_test:
        enable_test_user_provider: true
