imports:
    - { resource: sulu.yml }

sulu_admin:
    name: SULU 2.0
    email: installation.email@sulu.test

security:
    access_decision_manager:
        strategy: affirmative

    encoders:
        Sulu\Bundle\SecurityBundle\Entity\User: plaintext

    providers:
        testprovider:
            id: test_user_provider

    firewalls:
        test:
            http_basic:

sulu_security:
    checker:
        enabled: true

fos_rest:
    routing_loader:
        default_format: json

sulu_document_manager:
    default_session: default
    live_session: live

sulu_test:
    enable_test_user_provider: true
