imports:
    - { resource: sulu.yml }

sulu_admin:
    name: SULU 2.0
    email: installation.email@sulu.test

security:
    access_decision_manager:
        strategy: affirmative

    encoders:
        Sulu\Bundle\SecurityBundle\Entity\User: plaintext

    providers:
        testprovider:
            id: test_user_provider

    firewalls:
        test:
            logout_on_user_change: true
            http_basic:

sulu_security:
    checker:
        enabled: true

fos_rest:
    routing_loader:
        default_format: json

sulu_document_manager:
    default_session: default
    live_session: live

sulu_test:
    enable_test_user_provider: true

# Just a dirty hack to get the jms serializer bundle correctly working
# https://github.com/schmittjoh/JMSSerializerBundle/pull/270#issuecomment-21171800
services:
    jms_serializer.cache_naming_strategy: "@sulu_core.serialize_caching_strategy"
