framework:
    secret: secret
    router: { resource: '%kernel.root_dir%/config/routing.yml' }
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

# Monolog is needed for the webspace bundle
monolog:
    handlers:
        main:
            type:  'null'

sulu_core:
    cache_dir: '%kernel.root_dir%/cache/sulu'
    webspace:
        config_dir: "%kernel.root_dir%/Resources/webspaces"
    content:
        structure:
             default_type:
                snippet: 'default'
             paths:
                 pages:
                     path: '%kernel.root_dir%/Resources/pages'
                     type: page
                 homepage:
                     path: '%kernel.root_dir%/Resources/pages'
                     type: home
                 templates:
                     path: '%kernel.root_dir%/Resources/snippets'
                     type: snippet
    webspace: ~

doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            gedmo_tree:
                type: xml
                prefix: Gedmo\Tree\Entity
                dir: '%kernel.root_dir%/../../../../../../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity'
                alias: GedmoTree
                is_bundle: false
    dbal:
        url: '%database.url%'
        charset: '%database.charset%'
        default_table_options:
            charset: '%database.charset%'
            collate: '%database.collate%'

sulu_test:
    enable_test_user_provider: true

sulu_document_manager:
    sessions:
        default:
            backend:
                type: '%phpcr.transport%'
                url:  '%phpcr.backend_url%'
            workspace: '%phpcr.workspace%'
            username: '%phpcr.username%'
            password: '%phpcr.password%'
        live:
            backend:
                type: '%phpcr.transport%'
                url:  '%phpcr.backend_url%'
            workspace: '%phpcr.workspace%_live'
            username: '%phpcr.username%'
            password: '%phpcr.password%'
    debug: false

jms_serializer:
    metadata:
        debug: '%kernel.debug%'
