sulu_security.reset_password.email:
    path: reset/email
    defaults:
        _controller: sulu_security.resetting_controller:sendEmailAction

sulu_security.reset_password.reset:
    path: reset
    defaults:
        _controller: sulu_security.resetting_controller:resetAction
