sulu_security.reset_password.email:
    path: reset/email
    defaults:
        _controller: sulu_security.resetting_controller:sendEmailAction

sulu_security.reset_password.email.resend:
    path: reset/email/resend
    defaults:
        _controller: sulu_security.resetting_controller:sendEmailAction
        generateNewKey: false

sulu_security.reset_password.reset:
    path: reset
    defaults:
        _controller: sulu_security.resetting_controller:resetAction

sulu_security.contexts:
    type: rest
    name_prefix: sulu_security.
    resource: sulu_security.contexts_controller

sulu_security.profile:
    type: rest
    name_prefix: sulu_security.
    resource: sulu_security.profile_controller
