sulu_audience_targeting.target_group:
    path: "%sulu_audience_targeting.url%"
    defaults:
        _controller: sulu_audience_targeting.target_group_evaluation_controller:targetGroupAction

sulu_audience_targeting.target_group_hit:
    path: "%sulu_audience_targeting.hit.url%"
    defaults:
        _controller: sulu_audience_targeting.target_group_evaluation_controller:targetGroupHitAction
