Sulu\Bundle\ContentBundle\Document\HomeDocument:
    uri_schema: "/"
    token_providers:
        locale: [content_method, { method: getLocale }]
    conflict_resolver: throw_exception

Sulu\Bundle\ContentBundle\Document\PageDocument:
    uri_schema: "/{parent_locator}/{segment}"
    token_providers:
        parent_locator: [sulu_resource_locator, { parent: true, allow_empty: true }]
        segment: [content_method, { method: getResourceSegment, allow_empty: true, slugify: true  }]
    conflict_resolver: auto_increment
    defunct_route_handler: leave_redirect
