parameters:
    sulu_content.admin.class: Sulu\Bundle\ContentBundle\Admin\SuluContentAdmin
    sulu_content.twig_extension.class: Sulu\Bundle\ContentBundle\Twig\ContentExtension
    sulu_content.admin.content_navigation.class: Sulu\Bundle\ContentBundle\Admin\SuluContentContentNavigation
    sulu_content.preview.message_component.class: Sulu\Bundle\ContentBundle\Preview\PreviewMessageComponent
    sulu_content.preview.class: Sulu\Bundle\ContentBundle\Preview\Preview
    sulu_content.preview.lifetime: 3600
    sulu_content.preview.template-namespace: ClientWebsiteBundle:Website:
    sulu_content.preview.cache.class: Doctrine\Common\Cache\FilesystemCache
    sulu_content.node_repository.class: Sulu\Bundle\ContentBundle\Repository\NodeRepository
    sulu.content.type.smart_content.class: Sulu\Bundle\ContentBundle\Content\Types\SmartContent

services:
    sulu_content.admin:
        class: %sulu_content.admin.class%
        arguments: [%sulu_admin.name%]
        tags:
        - { name: sulu.admin }
    sulu_content.admin.content_navigation:
        class: %sulu_content.admin.content_navigation.class%
    sulu_content.twig_extension:
        class: %sulu_content.twig_extension.class%
        arguments: [@sulu.content.type_manager]
        tags:
            - { name: twig.extension }
    sulu_content.preview.cache:
        public: false
        class: %sulu_content.preview.cache.class%
        arguments: [%kernel.cache_dir%]
    sulu_content.preview:
        class: %sulu_content.preview.class%
        arguments:
            - @service_container
            - @templating
            - @sulu_content.preview.cache
            - @sulu.content.mapper
            - @sulu.content.structure_manager
            - @controller_resolver
            - %sulu_content.preview.lifetime%
            - %sulu_content.preview.template-namespace%
    sulu_content.preview.message_component:
        class: %sulu_content.preview.message_component.class%
        arguments: [@sulu_content.preview, @logger]
    sulu_content.node_repository:
        class: %sulu_content.node_repository.class%
        arguments: [@sulu.content.mapper, @sulu.phpcr.session, @sulu_security.user_manager]
    sulu.content.type.smart_content:
        class: %sulu.content.type.smart_content.class%
        arguments: [@sulu_content.node_repository, @sulu_tag.tag_manager, %sulu.content.type.smart_content.template%]
