sulu_admin:
    path:  /
    defaults:
        _controller: sulu_admin.admin_controller:indexAction

sulu_admin.widget_group:
    path: /widget-groups/{groupAlias}
    defaults: { _controller: SuluAdminBundle:WidgetGroups:group }

sulu_admin.navigation:
    type: rest
    resource: Sulu\Bundle\AdminBundle\Controller\NavigationsController

sulu_admin.content_navigation:
    type: rest
    resource: sulu_admin.content_navigation_controller

sulu_admin.routes:
    path: /bundles
    defaults:
        _controller: sulu_admin.admin_controller:bundlesAction

sulu_admin.config:
    path: /config
    defaults:
        _controller: sulu_admin.admin_controller:configAction

sulu_admin.contexts:
    path: /contexts
    defaults:
        _controller: sulu_admin.admin_controller:contextsAction

sulu_admin.login:
    path: /login
    defaults: { _controller: SuluAdminBundle:Security:login }

sulu_admin.reset:
    path: /reset/{token}
    defaults: { _controller: SuluAdminBundle:Security:reset }

sulu_admin.login_check:
    path: /login_check

logout:
    path: /logout
