sulu_admin:
    path:  /
    defaults:
        _controller: sulu_admin.admin_controller:indexAction

sulu_admin.config:
    path: /config
    defaults:
        _controller: sulu_admin.admin_controller:configAction

sulu_admin.metadata:
    path: /metadata/{type}/{key}
    defaults:
        _controller: sulu_admin.admin_controller:metadataAction

sulu_admin.translation:
    path: /translations
    defaults:
        _controller: sulu_admin.admin_controller:translationsAction

sulu_admin.login_check:
    path: /login

sulu_admin.logout:
    path: /logout

sulu_admin.reset:
    path: /reset/{token}
    defaults: { _controller: SuluAdminBundle:Security:reset }
