parameters:
    sulu_core.list_rest_helper.class: Sulu\Component\Rest\Listing\ListRestHelper
    sulu.phpcr.session.class: Sulu\Component\PHPCR\Session\SessionService
    phpcr_factoryClass: Jackalope\RepositoryFactoryJackrabbit
    sulu.content.mapper.class: Sulu\Component\Content\Mapper\ContentMapper
    sulu.content.structure_manager.class: Sulu\Component\Content\StructureManagerInterface
    sulu.content.type.text_line.class: Sulu\Component\Content\Types\TextLine
    sulu.content.type.text_area.class: Sulu\Component\Content\Types\TextArea
    sulu.content.type.resource_locator.class: Sulu\Component\Content\Types\ResourceLocator

services:
    sulu_core.list_rest_helper:
        class: %sulu_core.list_rest_helper.class%
        arguments: [@request, @doctrine.orm.entity_manager]
        scope: request
    sulu.phpcr.session:
        class: %sulu.phpcr.session.class%
        arguments: [%phpcr_factoryClass%, %phpcr_url%, %phpcr_username%, %phpcr_password%]
    sulu.content.mapper:
        class: %sulu.content.mapper.class%
        calls:
            - [ setContainer,[ @service_container ] ]
    sulu.content.structure_manager:
        class: %sulu.content.structure_manager.class%
        calls:
            - [ setContainer,[ @service_container ] ]
    sulu.content.type.text_line:
        class: %sulu.content.type.text_line.class%
    sulu.content.type.text_area:
        class: %sulu.content.type.text_area.class%
    sulu.content.type.resource_locator:
        class: %sulu.content.type.resource_locator.class%
        calls:
            - [ setContainer,[ @service_container ] ]
