parameters:
    sulu_translate.admin.class: Sulu\Bundle\TranslateBundle\Admin\SuluTranslateAdmin
    sulu_translate.import.class: Sulu\Bundle\TranslateBundle\Translate\Import
    sulu_translate.export.class: Sulu\Bundle\TranslateBundle\Translate\Export
    sulu_translate.admin.content_navigation.class: Sulu\Bundle\TranslateBundle\Admin\SuluTranslateContentNavigation

services:
    sulu_translate.admin:
        class: %sulu_translate.admin.class%
        arguments: [%sulu_admin.name%]
        tags:
            - { name: sulu.admin }
    sulu_translate.import:
        class: %sulu_translate.import.class%
        arguments: ["@doctrine.orm.entity_manager", "@kernel"]
    sulu_translate.export:
        class: %sulu_translate.export.class%
        arguments: ["@doctrine.orm.entity_manager"]
    sulu_translate.admin.content_navigation:
        class: %sulu_translate.admin.content_navigation.class%
