sulu_page.rl:
    type: rest
    name_prefix: sulu_page.
    resource: Sulu\Bundle\PageBundle\Controller\PageResourcelocatorController

sulu_page.resource_locator:
    type: rest
    name_prefix: sulu_page.
    resource: sulu_page.resource_locator_controller

sulu_page.page:
    type: rest
    name_prefix: sulu_page.
    resource: sulu_page.page_controller

sulu_page.post_page_trigger:
    path: /pages/{id}.{_format}
    methods: POST
    defaults:
        _controller: Sulu\Bundle\PageBundle\Controller\PageController::postTriggerAction
        _format: json

sulu_page.webspace.localization:
    type: rest
    name_prefix: sulu_page.
    resource: Sulu\Bundle\PageBundle\Controller\WebspaceLocalizationController

sulu_page.smart_content:
    type: rest
    name_prefix: sulu_page.
    resource: Sulu\Bundle\PageBundle\Controller\SmartContentItemController

sulu_page.webspace:
    type: rest
    name_prefix: sulu_page.
    resource: Sulu\Bundle\PageBundle\Controller\WebspaceController

sulu_page.teaser:
    type: rest
    name_prefix: sulu_page.
    resource: sulu_page.teaser_controller

sulu_page.page.versioning:
    type: versioning_rest
    resource: "@SuluPageBundle/Resources/config/routing_versioning_api.yml"
