sulu_media.collections:
    type: rest
    name_prefix: sulu_media.
    resource: sulu_media.collection_controller

sulu_media.post_collection_trigger:
    path: /collections/{id}.{_format}
    methods: POST
    defaults:
        _controller: sulu_media.collection_controller:postTriggerAction
        _format: json

sulu_media.media:
    type: rest
    name_prefix: sulu_media.
    resource: sulu_media.media_controller

sulu_media.post_media_trigger:
    path: /media/{id}.{_format}
    methods: POST
    defaults:
        _controller: sulu_media.media_controller:postTriggerAction
        _format: json

sulu_media.media_preview:
    type: rest
    name_prefix: sulu_media.
    parent: sulu_media.media
    resource: sulu_media.media_preview_controller

sulu_media.post_media_preview:
    path: /media/{id}/preview.{_format}
    methods: POST
    defaults:
        _controller: sulu_media.media_preview_controller:postAction
        _format: json

sulu_media.format:
    type: rest
    name_prefix: sulu_media.
    resource: sulu_media.format_controller

sulu_media.media_format:
    type: rest
    name_prefix: sulu_media.
    parent: sulu_media.media
    resource: Sulu\Bundle\MediaBundle\Controller\MediaFormatController
