sulu_media.website.image.proxy:
    path: "%sulu_media.format_cache.media_proxy_path%"
    defaults:
        _controller: sulu_media.media_stream_controller:getImageAction
        _requestAnalyzer: false
    requirements:
        slug: .*

sulu_media.website.media.download:
    path: "%sulu_media.media_manager.media_download_path%"
    defaults:
        _controller: sulu_media.media_stream_controller:downloadAction
        _requestAnalyzer: false
    requirements:
        slug: .*
